-- AlterTable
ALTER TABLE "leads" ADD COLUMN     "business_address" TEXT,
ADD COLUMN     "business_city" TEXT,
ADD COLUMN     "business_email" TEXT,
ADD COLUMN     "business_phone" TEXT,
ADD COLUMN     "business_state" TEXT,
ADD COLUMN     "business_zip" TEXT,
ADD COLUMN     "date_business_started" TEXT,
ADD COLUMN     "date_of_birth" TEXT,
ADD COLUMN     "dba" TEXT,
ADD COLUMN     "has_existing_loans" TEXT,
ADD COLUMN     "legal_entity" TEXT,
ADD COLUMN     "legal_name" TEXT,
ADD COLUMN     "nature_of_business" TEXT,
ADD COLUMN     "ownership_percentage" TEXT,
ADD COLUMN     "personal_address" TEXT,
ADD COLUMN     "personal_city" TEXT,
ADD COLUMN     "personal_state" TEXT,
ADD COLUMN     "personal_zip" TEXT,
ADD COLUMN     "social_security" TEXT,
ADD COLUMN     "state_of_inc" TEXT,
ADD COLUMN     "tax_id" TEXT;
